"""
Shared utilities for the Project Suraksha model pipeline.
Adapted for clean CSVs generated by data preprocessing.
"""

import os
import joblib
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score, f1_score

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BASE_DIR, "data")
MODEL_DIR = os.path.join(BASE_DIR, "models")
os.makedirs(MODEL_DIR, exist_ok=True)

RANDOM_STATE = 42
TEST_SIZE = 0.20
ID_COLS = ["village_code", "village_name", "subdistrict", "latitude", "longitude"]


def load_csv(filename):
    path = os.path.join(DATA_DIR, filename)
    if not os.path.exists(path):
        raise FileNotFoundError(f"Expected training file not found: {path}")
    return pd.read_csv(path)


def get_feature_cols(df, target_cols, extra_drop=None):
    drop = set(ID_COLS) | set(target_cols) | set(extra_drop or [])
    return [c for c in df.columns if c not in drop]


def split_feature_types(df, feature_cols):
    numeric_cols, categorical_cols = [], []
    for c in feature_cols:
        if pd.api.types.is_numeric_dtype(df[c]):
            numeric_cols.append(c)
        else:
            categorical_cols.append(c)
    return numeric_cols, categorical_cols


def build_preprocessor(df, feature_cols):
    numeric_cols, categorical_cols = split_feature_types(df, feature_cols)
    transformers = []
    if numeric_cols:
        transformers.append((
            "num",
            Pipeline([
                ("imputer", SimpleImputer(strategy="median")),
                ("scaler", StandardScaler()),
            ]),
            numeric_cols,
        ))
    if categorical_cols:
        transformers.append((
            "cat",
            Pipeline([
                ("imputer", SimpleImputer(strategy="most_frequent")),
                ("onehot", OneHotEncoder(handle_unknown="ignore")),
            ]),
            categorical_cols,
        ))
    return ColumnTransformer(transformers), numeric_cols, categorical_cols


def make_train_test_matrices(df, feature_cols, target_col, stratify=False):
    X = df[feature_cols]
    y = df[target_col].values
    X_train_raw, X_test_raw, y_train, y_test = train_test_split(
        X, y, test_size=TEST_SIZE, random_state=RANDOM_STATE,
        stratify=y if stratify else None,
    )
    preprocessor, num_cols, cat_cols = build_preprocessor(df, feature_cols)
    X_train = preprocessor.fit_transform(X_train_raw)
    X_test = preprocessor.transform(X_test_raw)
    if hasattr(X_train, "toarray"):
        X_train = X_train.toarray()
    if hasattr(X_test, "toarray"):
        X_test = X_test.toarray()
    return (X_train.astype("float32"), X_test.astype("float32"),
            y_train, y_test, preprocessor, num_cols, cat_cols)


def build_regression_model(input_dim, name="regressor"):
    keras.backend.clear_session()
    model = keras.Sequential([
        layers.Input(shape=(input_dim,)),
        layers.Dense(128, activation="relu"),
        layers.Dropout(0.2),
        layers.Dense(64, activation="relu"),
        layers.Dropout(0.1),
        layers.Dense(32, activation="relu"),
        layers.Dense(1, activation="linear"),
    ], name=name)
    model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=1e-3, clipnorm=1.0),
        loss="mse",
        metrics=["mae"],
    )
    return model


def build_classification_model(input_dim, num_classes, name="classifier"):
    keras.backend.clear_session()
    model = keras.Sequential([
        layers.Input(shape=(input_dim,)),
        layers.Dense(128, activation="relu"),
        layers.Dropout(0.2),
        layers.Dense(64, activation="relu"),
        layers.Dense(num_classes, activation="softmax"),
    ], name=name)
    model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=1e-3, clipnorm=1.0),
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"],
    )
    return model


def default_callbacks(patience=15):
    return [
        keras.callbacks.EarlyStopping(
            monitor="val_loss", patience=patience, restore_best_weights=True
        )
    ]


def run_regression_pipeline(df, feature_cols, target_col, model_name,
                            save_prefix, epochs=150, batch_size=32):
    print(f"\n--- {model_name} ---")
    print(f"Target: {target_col} | Feature count: {len(feature_cols)} | Rows: {len(df)}")
    (X_train, X_test, y_train, y_test,
     preprocessor, num_cols, cat_cols) = make_train_test_matrices(df, feature_cols, target_col)
    model = build_regression_model(X_train.shape[1], name=save_prefix)
    history = model.fit(
        X_train, y_train,
        validation_split=0.15,
        epochs=epochs,
        batch_size=batch_size,
        callbacks=default_callbacks(),
        verbose=0,
    )
    preds = model.predict(X_test, verbose=0).flatten()
    rmse = float(np.sqrt(mean_squared_error(y_test, preds)))
    r2 = float(r2_score(y_test, preds))
    print(f"Epochs trained: {len(history.history['loss'])} (early stopping)")
    print(f"Test RMSE: {rmse:.4f} | Test R2: {r2:.4f}")
    if r2 < 0.50:
        print(f"WARNING: R2={r2:.3f} is low for {target_col} - consider more features or data")
    keras_path = os.path.join(MODEL_DIR, f"{save_prefix}.keras")
    prep_path = os.path.join(MODEL_DIR, f"{save_prefix}_preprocessor.joblib")
    feat_path = os.path.join(MODEL_DIR, f"{save_prefix}_features.joblib")
    model.save(keras_path)
    joblib.dump(preprocessor, prep_path)
    joblib.dump(feature_cols, feat_path)
    return {"model_name": model_name, "algorithm": "Keras Dense NN (regression)",
            "task": f"Regression ({target_col})", "metric": f"R2={r2:.3f} / RMSE={rmse:.3f}",
            "saved_as": os.path.relpath(keras_path, BASE_DIR)}


def run_classification_pipeline(df, feature_cols, target_col, model_name,
                                save_prefix, epochs=150, batch_size=32):
    print(f"\n--- {model_name} ---")
    print(f"Target: {target_col} | Feature count: {len(feature_cols)} | Rows: {len(df)}")
    le = LabelEncoder()
    df = df.copy()
    df["_encoded_target"] = le.fit_transform(df[target_col].astype(str).to_numpy())
    num_classes = len(le.classes_)
    (X_train, X_test, y_train, y_test,
     preprocessor, num_cols, cat_cols) = make_train_test_matrices(
        df, feature_cols, "_encoded_target", stratify=True
    )
    model = build_classification_model(X_train.shape[1], num_classes, name=save_prefix)
    history = model.fit(
        X_train, y_train,
        validation_split=0.15,
        epochs=epochs,
        batch_size=batch_size,
        callbacks=default_callbacks(),
        verbose=0,
    )
    probs = model.predict(X_test, verbose=0)
    preds = np.argmax(probs, axis=1)
    acc = float(accuracy_score(y_test, preds))
    f1_weighted = float(f1_score(y_test, preds, average="weighted"))
    f1_macro = float(f1_score(y_test, preds, average="macro"))
    print(f"Epochs trained: {len(history.history['loss'])} (early stopping)")
    print(f"Test Accuracy: {acc:.4f} | F1(weighted): {f1_weighted:.4f} | F1(macro): {f1_macro:.4f}")
    print(f"Classes: {list(le.classes_)}")
    if acc < 0.70:
        print(f"WARNING: Accuracy={acc:.3f} is low for {target_col} - consider more data")
    keras_path = os.path.join(MODEL_DIR, f"{save_prefix}.keras")
    prep_path = os.path.join(MODEL_DIR, f"{save_prefix}_preprocessor.joblib")
    feat_path = os.path.join(MODEL_DIR, f"{save_prefix}_features.joblib")
    le_path = os.path.join(MODEL_DIR, f"{save_prefix}_label_encoder.joblib")
    model.save(keras_path)
    joblib.dump(preprocessor, prep_path)
    joblib.dump(feature_cols, feat_path)
    joblib.dump(le, le_path)
    return {"model_name": model_name, "algorithm": "Keras Dense NN (classification)",
            "task": f"Classification ({target_col})",
            "metric": f"Acc={acc:.3f} / F1(w)={f1_weighted:.3f}",
            "saved_as": os.path.relpath(keras_path, BASE_DIR)}


def run_confidence_pipeline(df, feature_cols, target_col, model_name,
                            save_prefix, epochs=150, batch_size=32):
    """
    Train a regression model that predicts model confidence.
    Uses leave-one-out cross-validation predictions on training data as target.
    """
    print(f"\n--- {model_name} (confidence estimation) ---")
    print(f"Target: {target_col} | Feature count: {len(feature_cols)} | Rows: {len(df)}")
    le = LabelEncoder()
    df = df.copy()
    df["_encoded_target"] = le.fit_transform(df[target_col].astype(str).to_numpy())
    num_classes = len(le.classes_)
    (X_train, X_test, y_train, y_test,
     preprocessor, num_cols, cat_cols) = make_train_test_matrices(
        df, feature_cols, "_encoded_target", stratify=True
    )
    model = build_classification_model(X_train.shape[1], num_classes, name=save_prefix)
    history = model.fit(
        X_train, y_train,
        validation_split=0.15,
        epochs=epochs,
        batch_size=batch_size,
        callbacks=default_callbacks(),
        verbose=0,
    )
    probs = model.predict(X_test, verbose=0)
    preds = np.argmax(probs, axis=1)
    acc = float(accuracy_score(y_test, preds))
    f1_weighted = float(f1_score(y_test, preds, average="weighted"))
    print(f"Epochs trained: {len(history.history['loss'])} (early stopping)")
    print(f"Test Accuracy: {acc:.4f} | F1(weighted): {f1_weighted:.4f}")
    keras_path = os.path.join(MODEL_DIR, f"{save_prefix}.keras")
    prep_path = os.path.join(MODEL_DIR, f"{save_prefix}_preprocessor.joblib")
    feat_path = os.path.join(MODEL_DIR, f"{save_prefix}_features.joblib")
    le_path = os.path.join(MODEL_DIR, f"{save_prefix}_label_encoder.joblib")
    model.save(keras_path)
    joblib.dump(preprocessor, prep_path)
    joblib.dump(feature_cols, feat_path)
    joblib.dump(le, le_path)
    return {"model_name": model_name, "algorithm": "Keras Dense NN (confidence)",
            "task": f"Classification confidence ({target_col})",
            "metric": f"Acc={acc:.3f} / F1(w)={f1_weighted:.3f}",
            "saved_as": os.path.relpath(keras_path, BASE_DIR)}


def run_explanation_pipeline(df, feature_cols, target_col, model_name,
                             save_prefix, epochs=150, batch_size=32):
    """
    Train a regression model that predicts the confidence score for a decision.
    """
    print(f"\n--- {model_name} (explanation/confidence) ---")
    print(f"Target: {target_col} | Feature count: {len(feature_cols)} | Rows: {len(df)}")
    X = df[feature_cols]
    y = df[target_col].values
    X_train_raw, X_test_raw, y_train, y_test = train_test_split(
        X, y, test_size=TEST_SIZE, random_state=RANDOM_STATE, stratify=y if len(np.unique(y)) > 1 else None,
    )
    preprocessor, num_cols, cat_cols = build_preprocessor(df, feature_cols)
    X_train = preprocessor.fit_transform(X_train_raw)
    X_test = preprocessor.transform(X_test_raw)
    if hasattr(X_train, "toarray"):
        X_train = X_train.toarray()
    if hasattr(X_test, "toarray"):
        X_test = X_test.toarray()
    model = build_regression_model(X_train.shape[1], name=save_prefix)
    history = model.fit(
        X_train, y_train,
        validation_split=0.15,
        epochs=epochs,
        batch_size=batch_size,
        callbacks=default_callbacks(),
        verbose=0,
    )
    preds = model.predict(X_test, verbose=0).flatten()
    rmse = float(np.sqrt(mean_squared_error(y_test, preds)))
    r2 = float(r2_score(y_test, preds))
    print(f"Epochs trained: {len(history.history['loss'])} (early stopping)")
    print(f"Test RMSE: {rmse:.4f} | Test R2: {r2:.4f}")
    keras_path = os.path.join(MODEL_DIR, f"{save_prefix}.keras")
    prep_path = os.path.join(MODEL_DIR, f"{save_prefix}_preprocessor.joblib")
    feat_path = os.path.join(MODEL_DIR, f"{save_prefix}_features.joblib")
    model.save(keras_path)
    joblib.dump(preprocessor, prep_path)
    joblib.dump(feature_cols, feat_path)
    return {"model_name": model_name, "algorithm": "Keras Dense NN (explanation)",
            "task": f"Regression confidence ({target_col})", "metric": f"R2={r2:.3f} / RMSE={rmse:.3f}",
            "saved_as": os.path.relpath(keras_path, BASE_DIR)}
